mysite/books/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url, include
from rest_framework import routers

from . import views

app_name = 'books'

router = routers.DefaultRouter()
router.register(r'authors', views.AuthorViewSet)
router.register(r'books', views.BookViewSet)
router.register(r'publishers', views.PublisherViewSet)

urlpatterns = [
    url('^$', views.index, name='index'),
    url('^meta/$', views.meta, name='meta'),
    url('^search_form/$', views.search_form, name='search_form'),
    url('^search/$', views.search, name='search'),
    url('^contact/$', views.contact, name='contact'),
    url('^contact/thanks/$', views.contact_thanks, name='contact_thanks'),
    url('^view1/$',
        views.requires_login(views.my_view1),
        name='requires_login'),
    url('^view2/$',
        views.requires_login(views.my_view2),
        name='requires_login'),
    url(r'^api/', include(router.urls)),
    url(r'^api-auth/',
        include('rest_framework.urls', namespace='rest_framework'))
]

mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('^polls/', include('polls.urls')),
    url('^books/', include('books.urls'))
]

mysite/polls/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url('^$', views.IndexView.as_view(), name='index'),
    url('^tribute/$', views.tribute, name='tribute'),
    url('^current_time/$', views.current_date, name='current_date'),
    url('^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url('^(?P<pk>[0-9]+)/results/$',
        views.ResultsView.as_view(),
        name='results'),
    url('^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote')
]

mysite/books/models.py
from django.db import models


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField(blank=True, verbose_name="e-mail")

    def __str__(self):
        return self.first_name + " " + self.last_name


class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __str__(self):
        return self.title

mysite/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(
            days=1) and self.pub_date < timezone.now()


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/books/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms


class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)

    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError('Not enough words')
        return message

mysite/books/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from django.views.decorators.csrf import csrf_exempt
from rest_framework import viewsets, permissions

from books.forms import ContactForm
from books.models import Author, Book, Publisher
from books.serializers import AuthorSerializer, BookSerializer, PublisherSerializer


def index(request):
    return HttpResponse('Hello')


def meta(request):
    template_name = 'books/meta.html'
    return render_to_response(template_name, {
        'meta': sorted(request.META.items())
    })


def search_form(request):
    return render_to_response('books/search_form.html')


def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if q:
            books = Book.objects.filter(title__icontains=q)
            return render_to_response('books/search_result.html', {
                'books': books,
                'query': q
            })
        elif len(q) > 20:
            errors.append('Enter a search term.')
        else:
            errors.append('Please enter at most 20 characters.')
    return render_to_response('books/search_form.html', {'errors': errors})


@csrf_exempt
def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            # cd = form.cleaned_data
            return HttpResponseRedirect('/books/contact/thanks/')
    else:
        form = ContactForm(initial={'subject': 'I love your site!'})
    return render_to_response('books/contact_form.html', {'form': form})


@csrf_exempt
def contact_thanks(request):
    return HttpResponse('thanks')


def requires_login(view):
    def new_view(request, *args, **kwargs):
        print('requires_login')
        if not request.user.is_authenticated():
            return HttpResponseRedirect('/accounts/login/')
        return view(request, *args, **kwargs)

    return new_view


def my_view1(request, *args, **kwargs):
    print('my_view1')
    return HttpResponse('view1')


def my_view2(request, *args, **kwargs):
    print('my_view2')
    return HttpResponse('view2')


class AuthorViewSet(viewsets.ModelViewSet):
    queryset = Author.objects.all().order_by('-first_name')
    serializer_class = AuthorSerializer
    permission_classes = (permissions.AllowAny,)


class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all().order_by('-publication_date')
    serializer_class = BookSerializer
    permission_classes = (permissions.AllowAny,)


class PublisherViewSet(viewsets.ModelViewSet):
    queryset = Publisher.objects.all()
    serializer_class = PublisherSerializer
    permission_classes = (permissions.AllowAny,)

mysite/polls/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, render_to_response
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from polls.models import Choice, Question


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        # return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(
            pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


def tribute(request):
    template_name = 'polls/tribute-page.html'
    return render(request, template_name)


def current_date(request):
    template_name = 'polls/current_date.html'
    now = datetime.datetime.now()
    return render_to_response(template_name, {"current_date": now})


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist) as e:
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You don't select a choice."
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(
            reverse('polls:results', args=(question.id, )))

mysite/books/templates/books/contact_form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>Contact us</title>
    </head>
    <body>
        <h1>Contact us</h1>
        {% if form.errors %}
            <p style="color:red;">Please correct the error{{ form.errors|pluralize }}</p>
        {% endif %}

        <form action="" method="post">
            <div class="field">
                {{ form.subject.errors }}
                <label for="id_subject">Subject:</label>
                {{ form.subject }}
            </div>
            <div class="field">
                {{ form.email.errors }}
                <label for="id_email">Your e-mail address:</label>
                {{ form.email }}
            </div>
            <div class="field">
                {{ form.message.errors }}
                <label for="id_message">Message:</label>
                {{ form.message }}
            </div>
            <input type="submit" name="" id="" value="Submit" />
        </form>
    </body>
</html>

mysite/books/templates/books/meta.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>meta</title>
    </head>
    <body>
        <table>
            {% for key, value in meta %}
            <tr>
            <td>{{ key }}</td>
            <td>{{ value }}</td>
            </tr>
            {% endfor %}
        </table>
    </body>
</html>

mysite/books/templates/books/search_form.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>search_form</title>
    </head>
    <body>
        {% if errors %}
            <ul>
                {% for error in errors %}
                <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="/books/search/" method="get">
            <input type="text", name="q">
            <input type="submit", value="Search">
        </form>
    </body>
</html>

mysite/books/templates/books/search_result.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width" />
        <title>search_result</title>
    </head>
    <body>
        <p>You searched for: <strong>{{ query }}</strong></p>

        {% if books %}
            <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
            <ul>
                {% for book in books %}
                    <li>{{ book.title }}</li>
                {% endfor %}
            </ul>
        {% else %}
            <p>No book matched your criteria</p>
        {% endif %}
    </body>
</html>

mysite/polls/templates/polls/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

mysite/polls/templates/polls/current_date.html
{% extends "polls/base.html" %}
{% block titile %}The current time{% endblock %}

{% block content %}
    <p>It is now {{ current_date|date:"F j, Y" }}.</p>
{% endblock %}

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br/>
{% endfor %}

<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <!--<a href="/polls/{{ question.id }}/">{{ question.question_text }}</a>-->
                <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            </li>
            {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

<a href="{% url 'polls:tribute' %}">tribute</a>
<a href="{% url 'polls:current_date' %}">current_time</a>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/tribute-page.html
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <title>Tribute page</title>
        <link rel="stylesheet"
              href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css"
              integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
              crossorigin="anonymous">
    </head>
    <style type="text/css" media="screen">
body {
    margin-top: 60px;
}
    </style>
    <body>
        <div class="container">
            <div class="jumbotron">
                <div class="row">
                    <div class="col-xs-12">
                        <h1 class="text-center">Dr. Norman Borlaug</h1>
                        <h2 class="text-center"><em>The man who saved a billion lives</em></h2>
                        <div class="thumbnail">
                            <img src="https://c2.staticflickr.com/4/3689/10613180113_fdf7bcd316_b.jpg">
                            <div class="caption text-center">
                                Dr. Norman Borlaug, third from left, trains
                                biologists in Mexico on how to increase wheat
                                yields - part of his life-long war on hunger.
                            </div>
                        </div>
                        <div class="col-xs-12 col-sm-10 col-sm-offset-1 col-md-8 col-md-offset-2">
                            <h3>Here's a time line of Dr. Borlaug's life:</h3>
                            <ul>
                                <li><strong>1914</strong>- Born in Cresco, Iowa</li>
                                <li><strong>1933</strong>- Leaves his family's
                                    farm to attend the University of Minnesota,
                                    thanks to a Depression era program known as
                                    the "National Youth Administration"</li>
                                <li><strong>1935</strong>- Has to stop school
                                    and save up more money. Works in the
                                    Civilian Conservation Corps, helping
                                    starving Americans. "I saw how food changed
                                    them", he said. "All of this left scars on
                                    me."</li>
                                <li><strong>1938</strong> - Marries wife of 69 years Margret Gibson. Gets laid off due to budget cuts. Inspired by Elvin Charles Stakman, he returns to school study under Stakman, who teaches him about breeding pest-resistent plants.</li>
                                <li><strong>1941</strong> - Tries to enroll in the military after the Pearl Harbor attack, but is rejected. Instead, the military asked his lab to work on waterproof glue, DDT to control malaria, disenfectants, and other applied science.</li>
                                <li><strong>1942</strong> - Receives a Ph.D. in Genetics and Plant Pathology</li>
                                <li><strong>1944</strong> - Rejects a 100% salary increase from Dupont, leaves behind his pregnant wife, and flies to Mexico to head a new plant pathology program. Over the next 16 years, his team breeds 6,000 different strains of disease resistent
                                    wheat - including different varieties for each major climate on Earth.</li>
                                <li><strong>1945</strong> - Discovers a way to grown wheat twice each season, doubling wheat yields</li>
                                <li><strong>1953</strong> - crosses a short, sturdy dwarf breed of wheat with a high-yeidling American breed, creating a strain that responds well to fertalizer. It goes on to provide 95% of Mexico's wheat.</li>
                                <li><strong>1962</strong> - Visits Delhi and brings his high-yielding strains of wheat to the Indian subcontinent in time to help mitigate mass starvation due to a rapidly expanding population</li>
                                <li><strong>1970</strong> - receives the Nobel Peace Prize</li>
                                <li><strong>1983</strong> - helps seven African countries dramatically increase their maize and sorghum yields</li>
                                <li><strong>1984</strong> - becomes a distinguished professor at Texas A&M University</li>
                                <li><strong>2005</strong> - states "we will have to double the world food supply by 2050." Argues that genetically modified crops are the only way we can meet the demand, as we run out of arable land. Says that GM crops are not inherently dangerous
                                    because "we've been genetically modifying plants and animals for a long time. Long before we called it science, people were selecting the best breeds."</li>
                                <li><strong>2009</strong> - dies at the age of 95.</li>
                            </ul>
                            <blockquote>
                                <p>"Borlaug's life and achievement are testimony to the far-reaching contribution that one man's towering intellect, persistence and scientific vision can make to human peace and progress."</p>
                                <footer>
                                    <cite>Indian Prime Minister Manmohan Singh</cite>
                                </footer>
                            </blockquote>
                            <h3>If you have time, you should read more about
                                this incredible human being on his <a
                             hreflang="https://en.wikipedia.org/wiki/Norman_Borlaug">Wikipedia
                             entry</a></h3>
                        </div>
                    </div>
                </div>
            </div>
            <footer class="text-center">
                <hr>
                <p>Written and coded by <a href=#>Robert Yang</a>.</p>
            </footer>
        </div>
    </body>
</html>